# Generated by Django 5.1.1 on 2024-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Введите имя', max_length=20, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите Email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
