# Generated by Django 5.1.1 on 2024-10-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок статьи",
                        max_length=50,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст статьи",
                        null=True,
                        verbose_name="содержимое",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="pictures/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="счётчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ("created_at",),
            },
        ),
    ]
