# Generated by Django 5.1.1 on 2024-10-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_massage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Massage",
        ),
    ]
