# Generated by Django 5.1.1 on 2024-10-12 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название рассылки",
                        max_length=100,
                        verbose_name="название",
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        help_text="Введите время (ЧЧ:ММ)", verbose_name="время отправки"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        help_text="Введите дату (ДД.ММ.ГГ)",
                        verbose_name="дата отправки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "день"), ("week", "неделя"), ("mon", "месяц")],
                        help_text="Выберите периодичность",
                        max_length=20,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("started", "запущена"),
                            ("completed", "завершена"),
                        ],
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="clients", to="main.client", verbose_name="клиенты"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Выберите сообщение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.message",
                        verbose_name="сообщение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
