# Generated by Django 5.1.1 on 2024-10-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('fio',), 'permissions': [('can_edit_is_active_client', 'Can edit active clients'), ('can_view_client_list', 'Can view client list')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('period',), 'permissions': [('can_edit_is_active_mailing', 'Can edit active mailing'), ('can_change_clients_mailing', 'Can_change_clients_mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
