# Generated by Django 5.1.1 on 2024-10-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_client_options_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
    ]
