# Generated by Django 5.1.1 on 2024-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_client_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("date_start", "time_start"),
                "permissions": [
                    ("can_edit_is_active_mailing", "Can edit active mailing"),
                    ("can_change_clients_mailing", "Can change clients mailing"),
                    ("can_view_clients_mailing", "Can view clients mailing"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
    ]
