# Generated by Django 5.1.1 on 2024-10-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_mailing_options_alter_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('date_start', 'time_start'), 'permissions': [('can_edit_is_active_mailing', 'Can edit active mailing'), ('can_change_clients_mailing', 'Can change clients mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
