# Generated by Django 5.1.1 on 2024-10-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Клиент'),
        ),
    ]
